Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
Traceback (most recent call last):
  File "/home/patri/Documents/Codes/moje-clanky-core/news-recommender-core/rabbitmq_multithreaded_thumbs.py", line 6, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
